"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Sidebar from "./Components/Sidebar";
import { SessionProvider } from "next-auth/react";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark text-foreground bg-background">
        <SessionProvider>
          <NextUIProvider>
            <div className=" w-full h-screen">
              <Sidebar />

              {children}
            </div>
          </NextUIProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
